version: "3.9"

services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "meuportefolio!23"
    volumes:
      - sqlportfolio_data:/var/opt/mssql
    ports:
      - "1433:1433"

  api:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    environment:
      DATABASE_URL: "Server=db,1433;Database=meuportefolio;User Id=sa;Password=meuportefolio!23;TrustServerCertificate=true"
    depends_on:
      - db
    ports:
      - "8080:8080"

volumes:
  sqlportfolio_data:
